### ISSUE TITLE
mustread.tech is down

### ISSUE THREAD

**Issue by avisnakovs** [sizovs/mustread-data#37]
Is **mustread.tech** going to be live again?

Here I also found [reddit thread](https://www.reddit.com/r/programming/comments/s2x8wa/is_mustreadtech_down_for_good/) regarding this issue.

**Comment by sizovs** [comment]
Hey @avisnakovs! 

The domain has expired, and the project is dead for now. The data is available in this repo, and the code is [here](https://github.com/sizovs/mustread).

Do you think it's worth re-creating?

**Comment by avisnakovs** [comment]
Hey, 

Don't know if it worth recreating since domain is expired. 
Maybe it could be set up without custom domain - with default github domain name **https://sizovs.github.io/mustread/**

Although, I only occasionally visit this project - local setup is enough for me.
